server:
  port: 8091
spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/gate2innovatedb
    username: hridaysarma
    password: Thisistest@123
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
upload:
  path: "/var/www/upload"

application:
  security:
    jwt:
      secret-key: 66556A586E327234753778214125442A472D4B6150645367566B597033733676
      expiration: 86400000 # a day
      refresh-token:
        expiration : 604800000 # a week


